name: Deploy Package to NPM

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Instalando NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 14.7

      - name: Instalando Pacotes
        run: yarn

      - name: Fazendo Bump da Versão do Pacote
        uses: ramonpaolo/bump-version@v1.0.1

      - name: Publicando package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}